### ISSUE TITLE
Document how this is actually supposed to be used

### ISSUE THREAD

**Issue by l0b0** [linz/linz-software-repository#150]
For one thing,

```yaml
on:
  push:
    branches:
      - master
    tags: ['*']
  pull_request:
    types: [opened, reopened, synchronize]
```

is not sufficient to trigger a build when CI creates a commit to add the Debian change log.
